apiVersion: v1
kind: Secret
metadata:
  name: arc-runner-ci-token
  namespace: arc-runners
  annotations:
    kubernetes.io/service-account.name: arc-runner-set-gha-rs-no-permission
type: kubernetes.io/service-account-token
